version: 1
project:
  authors:
    - id: student
      name: Student Name
      affiliations:
        - tud

  contributors:
    - id: supervisor-1
      name: The Supervisor
      affiliations:
        - tud
    - id: committee-1
      name: Prof. Dr. Committee Member
      affiliations:
        - tud
    - id: committee-2
      name: Dr. Committee Member
      affiliations:
        - tud

  affiliations:
    - id: tud
      institution: Delft University of Technology
      #city: Delft
      #country: Netherlands
